export const API_ERROR_CODE = {
    // region Genaral
    ER_PAGESIZE_REQUIRED: 4,
    ER_PAGEINDEX_REQUIRED: 5,
    ER_PAGESIZE_LESS_THAN_OR_EQUAL_50: 6,
    ER_DOMAIN_NOT_SUPPORT: 7,
    ER_INVALID_FILE_TYPE: 8,
    ER_INVALID_FILE_TEMPLATE_EXCEL: 9,
    // endregion

    // region User
    ER_USER_NOT_EXISTS: 100,
    ER_USER_NOT_ACTIVE: 101,
    ER_USER_PASSWORD_INCORRECT: 102,
    ER_USER_INVALID_REFRESH_TOKEN: 103,
    ER_USER_ALREADY_EXISTS: 104,
    // endregion

    // region Production Plan
    ER_PRODUCTION_PLAN_FILE_NOT_EXISTS: 201,
    ER_PRODUCTION_PLAN_ERROR_PARSE_FILE: 202,
    ER_PRODUCTION_PLAN_NOT_EXISTS: 203,
    ER_PRODUCTION_PLAN_NOT_PENDING: 204,
    ER_PRODUCTION_PLAN_START_TIME_INVALID: 205,
    ER_PRODUCTION_PLAN_MATERIAL_NOT_READY: 206,
    ER_PRODUCTION_PLAN_MOLD_NOT_READY: 207,
    ER_PRODUCTION_PLAN_NOT_READY: 208,
    ER_PRODUCTION_PLAN_NOT_TESTING: 209,
    ER_PRODUCTION_PLAN_NOT_TEST_DONE: 210,
    ER_PRODUCTION_PLAN_NOT_RUNNING: 211,
    ER_PRODUCTION_PLAN_NOT_EXISTS_MACHINE_CODE: 212,
    ER_PRODUCTION_PLAN_NOT_EXISTS_MOLD_CODE: 213,
    ER_PRODUCTION_PLAN_NOT_EXISTS_MATERIAL_CODE: 214,
    ER_PRODUCTION_MACHINE_DRYER_CODE_NOT_EXISTS: 215,
    ER_PRODUCTION_MACHINE_DRYER_NOT_PREPARED: 216,
    ER_PRODUCTION_PLAN_NOT_PAUSED: 217,
    ER_PRODUCTION_PLAN_NO_ROW_VALID: 218,
    // endregion

    // region Product Management
    ER_PRODUCT_CODE_ALREADY_EXISTS: 301,
    ER_PRODUCT_NOT_EXISTS: 302,
    ER_PRODUCT_IMPORT_TCKT_NGOAI_QUAN: 303,
    // endregion

    // region Production Plan QC Assign
    ER_PRODUCTION_PLAN_QC_ASSIGNED: 401,
    ER_PRODUCTION_PLAN_QC_NOT_EXISTS: 402,
    ER_PRODUCTION_PLAN_QC_ASSIGNED_MAX: 403,
    // endregion

    // region Employee
    ER_NOT_BELONG_PHONG_KY_THUAT: 501,
    ER_NOT_BELONG_QUAN_LY_SAN_XUAT: 502,
    // endregion

    // region QC Test Result
    ER_QC_TEST_RESULT_EXISTS_BY_OTHERS: 601,
    ER_QC_TEST_RESULT_NOT_FOUND: 602,
    // endregion

    // region Mold Setup Time Config
    ER_MOLD_SETUP_TIME_CONFIG_NOT_EXISTS: 701,
    // endregion

    // region Material Drying Setup Time Config
    ER_MATERIAL_DRYING_SETUP_TIME_CONFIG_NOT_EXISTS: 801,
    // endregion
};
