export const PUB_TOPIC = {
    UNAUTHORIZED_REQUEST: 'UNAUTHORIZED_REQUEST',
    ENTITY_TOO_LARGE: 'ENTITY_TOO_LARGE',
    NETWORK_ERROR: 'NETWORK_ERROR',
    RECALL_PRODUCT: 'RECALL_PRODUCT',
    RECALL_PRODUCTION_PLAN: 'RECALL_PRODUCTION_PLAN'
};